### ISSUE TITLE
Error/Freezes When Ordering Cards on Kanban Board

### ISSUE THREAD

**Issue by jarrettbarnett** [dylang/jira-improved#4]
![screen shot 2015-11-20 at 9 27 56 am](https://cloud.githubusercontent.com/assets/265853/11306821/10858bcc-8f69-11e5-81d2-3834f7dbfdf1.png)
![screen shot 2015-11-20 at 9 28 09 am](https://cloud.githubusercontent.com/assets/265853/11306822/1085ac92-8f69-11e5-9d0c-ed894e3662fd.png)

Perhaps it has to do with the fields I do/don't have visible on my board?

These fields are currently configured to show on cards:
![screen shot 2015-11-20 at 9 29 00 am](https://cloud.githubusercontent.com/assets/265853/11306851/3e78ef06-8f69-11e5-9ac5-d591c5c96964.png)

**Comment by dylang** [comment]
Hi, thanks for creating the issue. 

Has this always been happening or is it new? Do you know what version of Jira you are using? 

These sort of things are painful to debug because of Jira plugins and changes between versions can easily break Jira Improved. 

I appreciate that you included the screenshot from the console. It looks like in the stack dump this error is happening in the Jira code, and not the plugin. 

The fields you've picked shouldn't come into play, and now that I think about it, my version of Jira is kinda old and doesn't let us pick what is on each card. That's one of the reasons I made the plugin. It's possible that the plugin is not compatible with your version of Jira, and I'm not sure how to fix that without access to a newer version of Jira.

**Comment by jarrettbarnett** [comment]
I only recently started using this extension, so both "always and new". :)

We're using JIRA v6.3.12.

I dug in a little more. Probably won't be enough to help without direct access (like you said) but maybe it will shed some light on the issue.

Here's the error expanded:
![screen shot 2015-11-20 at 10 10 16 am](https://cloud.githubusercontent.com/assets/265853/11307869/c73d3b5c-8f6f-11e5-9023-3e8fe3198b1c.png)

Here's an error that happens on page load.
![screen shot 2015-11-20 at 10 12 04 am-modified](https://cloud.githubusercontent.com/assets/265853/11307864/bd9c07e0-8f6f-11e5-94d5-9a3c1483d222.jpg)

Thanks for your time either way.
